version: "2"

services:
  master:
    image: singularities/spark
    command: start-spark master
    hostname: master
    ports:
      - "6066:6066"
      - "7070:7070"
      - "8080:8080"
      - "50070:50070"
  worker:
    image: singularities/spark
    command: bash -c 'sed -i "s|\[NAMENODE_HOST\]|master|g" /usr/local/hadoop-2.7.3/etc/hadoop/core-site.xml && start-spark worker master'
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g
      PYSPARK_PYTHON: python3
    links:
      - master
